### ISSUE TITLE
Working with Docker

### ISSUE THREAD

**Issue by guillaumepn** [sysgears/apollo-universal-starter-kit#868]
I've been playing with this starter and would like to use it for a small team project, but I find the `docker-compose up` command taking a bit long (about 5 minutes), mainly, I guess, because of the yarn command in docker-compose that install the long list of packages from package.json

Is there a way around it ? 

I know the long first build is a necessary step, but after the first `docker-compose up`, I tried removing the `yarn` commands from docker-compose.yml, because I saw there was a volume for node_modules/ so I thought it was unnecessary to keep it after the first occurrence, but after I restarted Docker today and run the project again, I got an error that I could only fix by running the yarn cmd again in Docker

Do you have more info than the Get started wiki, about how to use with Docker ?

**Comment by vlasenko** [comment]
@guillaumepn There are solutions to this problem, though they are quite complicated. Example:
https://hackernoon.com/using-yarn-with-docker-c116ad289d56
We are open to pull requests to improve docker scripts.

**Comment by vlasenko** [comment]
@guillaumepn `docker-compose up` command on the second run takes  around 1 minute and 20 seconds for me. yarn runs for 55 secs and server+web build starts for 25 secs. It is certainly not 5 minutes, though I agree it would be great to cut down these 55 secs taken by yarn.

**Comment by guillaumepn** [comment]
I've tried the following docker-compose (I'm using PostgreSQL) : 

don't know if the small changes I've brought to the volumes had any effect, but it now takes about 1 minute to run (notice I commented out the yarn command, because I only do it the first time), which is pretty decent, and I've tried stopping the containers, stopping Docker, restarting it, now all data seem to be ok, I didn't have to re-run the yarn cmd :D 

```yaml
version: '3'
services:
  node:
    build:
      context: .
      args:
        APP_DIR: ${APP_DIR}
    environment:
    - NODE_ENV=development
    container_name: apollo_universal_starter
    tty: true
    stdin_open: true
    links:
      - db
    volumes:
    - ./:${APP_DIR}
    - ./build:${APP_DIR}/build
    - ./node_modules:${APP_DIR}/node_modules
    working_dir: ${APP_DIR}
    user: node
    command: >
      sh -c '
      exec yarn watch
      '
#      yarn &&
#      (test -f dev-db.sqlite3 || yarn seed) &&
    ports:
    - 3000:3000
    - 3010:3010
    - 3020:3020
    - 8080:8080
    - 19000:19000
    - 19001:19001

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: docker
    ports:
    - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql

  adminer:
    image: adminer
    ports:
    - 8989:8080
```
